# Generated by Django 3.0.8 on 2020-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_id', models.PositiveIntegerField(default=1)),
                ('end_id', models.PositiveIntegerField(default=1000)),
                ('current_id', models.PositiveIntegerField(default=0)),
                ('previous_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Counter',
            },
        ),
    ]
