# Generated by Django 3.0.8 on 2020-07-20 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shortened_url', models.URLField(blank=True, db_index=True, unique=True)),
                ('full_url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'ShortURL',
                'verbose_name_plural': 'ShortURLs',
                'ordering': ['shortened_url'],
            },
        ),
    ]
